const descMap = new Map<string, string>([
    ["epochs", "Epochs represent the number of times the entire training dataset is passed through the learning algorithm during training."],
    ["batchSize", "Batch size refers to the number of samples that are passed to the network at once during training, influencing training speed and model performance."],
    ["learningRate", "Learning rate controls the rate at which the model learns by determining the size of weight updates during training."],
    ["optimizer", "Optimizers are algorithms used to adjust the model's parameters, such as weights and learning rate, in order to minimize the loss function and improve the model's performance."],
    ["loss", "Loss function measures how well the model's predicted outputs match the true output labels, and is used to optimize the model by minimizing the loss during training."],
    ["trainTestRatio", "Dataset is split into two subsets, where the training set (typically 70-80% of the data) is used to fit a machine learning model and the test set (typically 20-30% of the data) is used to evaluate the model's performance on unseen data"],
    ["activation", "Activation function calculates the output of a node in a network based on its inputs and weights."],
    ["confusionMatrix", "Consfusion matrix helps..."],
    ["accuracy", "Accuracy is a measure..."],
    ["precision", "Precision is a measure..."],
    ["recall", "Recall is a measure..."],
    ["features", "Features are..."],
    ["classes", "Classes are..."],
    ["hiddenLayer", "Hidden layer is..."],
    ["inputLayer", "Input layer..."],
    ["outputLayer", "Output layer..."],
    ["filterCount", ""],
    ["filterSize", ""],
    ["stride", ""],
    ["padding", ""],
    ["poolSize", ""],
    ["", ""],
]);

export default descMap;